on: [workflow_dispatch]
name: AzureWebAppContainer
env:
  CONTAINER_REGISTRY: learnacr402mr.azurecr.io
jobs:
  azurecontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: ACR Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: learnacr402mr
          password: ${{ secrets.ACR_PWD }}
      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'runappaeae'
          images: ${{ env.CONTAINER_REGISTRY }}/nginx:mycopy
